### ISSUE TITLE
page fault when run on a 486 without any sound card installed

### ISSUE THREAD

**Issue by goshhhy** [goshhhy/486quake#2]

**Comment by werratai** [comment]
I can't get sound to play on the retail exe.  It's initing the sbpro2 clone at 8 bit 11khz but maybe the whole thing is too slow for sound.  Hangs on the DOS screen at 'Playing Registered Version'

**Comment by leilei-** [comment]
It's an old regression starting in v1.07 (Scourge of Armagon)

**Comment by goshhhy** [comment]
do you happen to know the cause/fix? 

(i haven't looked into this at all, i've spent basically all of my time on optimization work)

**Comment by goshhhy** [comment]
@leilei- do you happen to know the cause/fix?

(i haven't looked into this at all, i've spent basically all of my time on optimization work)

**Comment by goshhhy** [comment]
fixed in 334b05a
