### ISSUE TITLE
What are you using to measure performance?

### ISSUE THREAD

**Issue by jheronimus** [goshhhy/486quake#9]
Hi!

I'm testing 486quake on an AMD 5x86 system using PC Chips M919 board v3.3. I have 32MB 60ns FPM RAM installed and also the 256KB cache stick. The videocard is Ark Logic 1000VL (VLB), the hard drive is a PIO mode 4 Quantum.

The CPU was overclocked to 160 MHz, all the cache and RAM timings are tweaked to the lowest setting. The BIOS is 10/16/1996 (the lowest I know so far).

I'm running timedemo demo1 on a shareware version of Quake 1.06 with -nosound -nocdaudio and I get 19.1FPS. The OS is DOS 6.22.

Which is weird, because in your results you have 18.4 for a system that was not overclocked and has no cache. Initially I set the system to write-through cache by mistake, and that alone gave me 0.5FPS difference, so having extra speed on CPU and video must surely get me into 20-21FPS range, but it does not.

So I wanted to ask, how did you run your test? Was it timedemo demo1? Did you have sound and CD audio disabled?

On a related note, I could not get the FPS counter in 486quake. /cg_drawfps 1 does nothing — says, the command is not found.

**Comment by jheronimus** [comment]
Ran the benchmark on a Ali M1489 board (DataExpert EXP8449) with Ark Logic 2000PV running on a 40MHz PCI bus, 32MB FPM RAM, 256KB L2 Cache. PIO Mode 4 enabled, IDE drivers installed for DOS.

Also 19.1 FPS in timedemo demo1 -nosound -nocdaudio.

I'm a bit suprised there is no further improvement to FPS.

**Comment by goshhhy** [comment]
i use `quake.exe -nosound -nocdaudio +timedemo demo1`.

my results tend to be dramatically different based on the exact hardware configuration - specifically, the motherboard chipset, ram, and video card - but is very stable on the same hardware.
